### ISSUE TITLE
Adding PYTH Oracle Integration To Official Doc

### ISSUE THREAD

**Issue by ezekiel6262** [FuelLabs/Pyth-integration#33]
Adding PYTH Oracle to the official Fuel Network document should be essential. This integration will be useful for developers to identify the oracles and price feed providers when building on Fuel Network. 
Link : https://docs.fuel.network/
To be Added : PYTH Integration/ Price Feed

This integration is to informed developers and collaborators one of the best integration in Fuel Network.
More so, Issues with the PYTH Integration needs some work done, there are few errors in the Codebase that needs to be solve, Following the document path (Price Feed Event) : pyth-contract/src/errors.sw

**Comment by K1-R1** [comment]
Thanks for opening the issue. As the integration has not been officiated by the Pyth team yet, we are unable to add it to the official docs for now. 
For further details this comment on a similar issue may be of use for context: https://github.com/FuelLabs/Pyth-integration/issues/8#issuecomment-1952816207

**Comment by ezekiel6262** [comment]
Awesome. Thanks for the heads up
