### ISSUE TITLE
Price relayer

### ISSUE THREAD

**Issue by K1-R1** [FuelLabs/Pyth-integration#8]
- [ ] #12 
- [ ] #13
- [ ] #14
- [ ] #15

Pyth's Hermes web service is available to use for price data relaying: https://docs.pyth.network/documentation/pythnet-price-feeds/hermes
Usage example via Pyth's JS SDK can be found here: https://github.com/pyth-network/pyth-crosschain/tree/main/target_chains/ethereum/sdk/js

**Comment by ezekiel6262** [comment]
Can we solve this ?
